spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/taskdb?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:Sonam@9022}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}